notifications/authentication/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetView


from .views import (RegisterView,
                    UserLoginView,
                    UserLogoutView,
                    UserProfileView,
                    attaching_telegram_account_dispetcher,
                    dispetcher_providing_networks,
                    SenderInformationView,
                    activate_sender_network,
                    delete_telegram,
                    ChangeUserEmail,
                    verificate_user_email,
                    activate_user_email,
                    )     

app_name = 'auth'

urlpatterns = [
    path('registration/', RegisterView.as_view(), name="registration"),
    path('login/', UserLoginView.as_view(), name="login"),
    path('logout/', UserLogoutView.as_view(), name="logout"),
    path('profile/', UserProfileView.as_view(), name="profile"),
    path('telegram/', attaching_telegram_account_dispetcher, name="register_tg"),
    path('profile/dispetcher_providing_networks/<slug:slug>/', dispetcher_providing_networks, name="dispetcher_providing_networks"),
    path('profile/sender_info/<slug:slug>/', SenderInformationView.as_view(), name="sender_information"),
    path('profile/activate/<uuid:pk>/', activate_sender_network, name="activate_sender_network"),
    path('profile/delete_telegram/<uuid:pk>/', delete_telegram, name='delete_telegram'),
    path('profile/change_user_email/<uuid:pk>/', ChangeUserEmail.as_view(), name='changing_user_email'),
    path('profile/verificate_user_email/', verificate_user_email, name='verificate_user_email'),
    path('activate_user_email/<uidb64>/<token>/', activate_user_email, name='activate_user_email'),
    
    path('reset_password/', PasswordResetView.as_view(template_name='auth/email/reset_password/reset_password.html',
                                                                 html_email_template_name='auth/email/reset_password/reset_password_email.html'),
                                                                 name="password_reset"),
    path('reset_password_sent/', PasswordResetDoneView.as_view(template_name='auth/email/reset_password/reset_password_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='auth/email/reset_password/reset_password_confirm.html'),name="password_reset_confirm"),
    path('reset_password_complete/', PasswordResetCompleteView.as_view(template_name='auth/email/reset_password/reset_password_complete.html'),name="password_reset_complete"),

]

notifications/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from notifications.views import redirect_user_view


urlpatterns = i18n_patterns(
    path('', redirect_user_view, name="redirect_user_view"),
    path('admin/', admin.site.urls),

    # api notifications
    path('api_notifications/', include(('notifications.notifications_api.urls', 'notifications_api'), namespace="notifications_api")),

    # Notifications
    path('notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),

    # Notification Categories
    path('notification_categories/', include(('notification_categories.urls', 'notification_categories'), namespace='notification_categories')),

    # api notification categories
    path('api_notification_categories/', include(
            ('notification_categories.notification_categories_api.urls', 'notification_categories_api'),
            namespace='notification_categories_api'
        )
    ),

    # Auth
    path('api-auth/', include(('authentication.authentication_api.urls', 'api-auth'), namespace="api-auth")),


    path('auth/', include(('authentication.urls', 'auth'), namespace='auth')),

)

handler404 = 'core.views.not_found_404'
hhandler500 = 'core.views.server_error_500'

notifications/notifications/notifications_api/urls.py
from django.urls import path

from .api_views import (
    NotificationListApiView,
    NotificationFinishedListApiView,

    NotificationSingleDetailApiView, 
    NotificationSingleCreateApiView, 
    NotificationSingleEditApiView, 
    NotificationSingleDeleteApiView,

    NotificationPeriodicDetailApiView, 
    NotificationPeriodicCreateApiView,
    NotificationPeriodicDeleteApiView, 
    NotificationPeriodicEditApiView,

    NotificationPeriodicTimeStampsListApiView,
    NotificationPeriodicRevokeCertainTimeStampApiView,
    NotificationPeriodicRevokeAllTimeStampsApiView,

    ChangeNotificationStatusFromRevokeToIncompleteApi
)

app_name = "notifications_api"

urlpatterns = [
    path('notifications_list/', NotificationListApiView.as_view(), name='notifications_list_api'),
    path('finished_notifications_list/', NotificationFinishedListApiView.as_view(), name='finished_notifications_list_api'),

    path('create_notification_single/', NotificationSingleCreateApiView.as_view(), name='create_notification_single_api'),
    path('edit_notification_single/<uuid:pk>/', NotificationSingleEditApiView.as_view(), name='edit_notification_single_api'),
    path('delete_notification_single/<uuid:pk>/', NotificationSingleDeleteApiView.as_view(), name='delete_notification_single_api'),
    path('single/<uuid:pk>/', NotificationSingleDetailApiView.as_view(), name='notification_single_detail_api'),

    path('create_notification_periodic/', NotificationPeriodicCreateApiView.as_view(), name='create_notification_periodic_api'),
    path('delete_notification_periodic/<uuid:pk>/', NotificationPeriodicDeleteApiView.as_view(), name='delete_notification_periodic_api'),
    path('edit_notification_periodic/<uuid:pk>/', NotificationPeriodicEditApiView.as_view(), name='edit_notification_periodic_api'),
    path('periodic/<uuid:pk>/', NotificationPeriodicDetailApiView.as_view(), name='notification_periodic_detail_api'),

    path('notification_periodic_time_stamps_list/<uuid:pk>/', NotificationPeriodicTimeStampsListApiView.as_view(), name='notification_periodic_time_stamps_list_api'),
    path('revoke_certain_notification_time_stamp/<uuid:pk>/', NotificationPeriodicRevokeCertainTimeStampApiView.as_view(), name='notification_periodic_revoke_certain_time_stamp_api'),
    path('revoke_all_notification_time_stamp/<uuid:pk>/', NotificationPeriodicRevokeAllTimeStampsApiView.as_view(), name='notification_periodic_revoke_all_time_stamps_api'),

    path('change_notification_status_from_revoke_to_incomplete/<uuid:pk>/', ChangeNotificationStatusFromRevokeToIncompleteApi.as_view(), name='change_notification_status_from_revoke_to_incomplete_api')

]

notifications/notifications/urls.py
from django.urls import path
from .views import (
    NotificationListView,
    NotificationSingleCreateView,
    NotificationSingleEditView, 
    NotificationSingleDeleteView,
    NotificationSingleDetailView, 
    PeriodicalNotificationCreateView,
    NotificationPeriodicDetailView,
    NotificationPeriodicListTimeStampsView,
    NotificationPeriodicRevokeCertainTimeStampView,
    NotificationPeriodicRevokeAllTimeStampsView,
    notificatePeriodicNotificationOnlyForAdmin,
    notificateSingleNotificationOnlyForAdmin,
    NotificationPeriodicDeleteView,
    NotificationPeriodicEditView,
    NotificationFinishedListView,
    change_notification_status_from_revoke_to_incomplete,
    SearchNotificationView
)

app_name = 'notifications'

urlpatterns = [
    path('read/', NotificationListView.as_view(), name="notification_list"),
    path('finished/', NotificationFinishedListView.as_view(), name="notification_archive_list"),

    path('create/', NotificationSingleCreateView.as_view(), name="create_notification"),
    path('create_periodical_notification/', PeriodicalNotificationCreateView.as_view(), name="create_periodical_notification"),
    path('edit/<uuid:pk>/', NotificationSingleEditView.as_view(), name="edit_notification"),
    path('edit_periodic/<uuid:pk>/', NotificationPeriodicEditView.as_view(), name="edit_periodic_notification"),
    path('delete/<uuid:pk>/', NotificationSingleDeleteView.as_view(), name="delete_notification"),
    path('delete_periodic/<uuid:pk>/', NotificationPeriodicDeleteView.as_view(), name="delete_periodic_notification"),
    path('single/<uuid:pk>/', NotificationSingleDetailView.as_view(), name="detail_single_notification"),
    path('periodic/<uuid:pk>/', NotificationPeriodicDetailView.as_view(), name="detail_periodic_notification"),

    path('notification_periodic_time_stamps_list/<uuid:pk>/', NotificationPeriodicListTimeStampsView.as_view(), name="notification_periodic_time_stamps_list"),
    path('revoke_certain_time_stamp/detail/<uuid:pk>/', NotificationPeriodicRevokeCertainTimeStampView.as_view(), name="notification_periodic_revoke_certain_time_stamp"),
    path('revoke_all_time_stamps/<uuid:pk>/', NotificationPeriodicRevokeAllTimeStampsView.as_view(), name="notification_periodic_revoke_all_time_stamps"),

    path('notificate_periodic_notification_only_for_admin/<uuid:pk>/', notificatePeriodicNotificationOnlyForAdmin, name="notificate_periodic_notification_only_for_admin"),
    path('notificate_single_notification_only_for_admin/<uuid:pk>/', notificateSingleNotificationOnlyForAdmin, name="notificate_single_notification_only_for_admin"),

    path('change_notification_status_from_revoke_to_incomplete/<uuid:pk>/', change_notification_status_from_revoke_to_incomplete, name="change_notification_status_from_revoke_to_incomplete"),

    path('search/', SearchNotificationView.as_view(), name='search_results'),

]

notifications/templates/notifications/CUD_notifications/create_notification.html
{% extends 'base.html' %}
{% load i18n crispy_forms_tags %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Creating single notification' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Creating single notification' %}" />
    <meta property="og:url" content="{% url 'notifications:create_notification' %}" />
{% endblock meta_tags %}

{% block style %}
    <style>
        #div_id_notification_date > div {
            display: flex;
        }
        #id_notification_date_day, #id_notification_date_month, #id_notification_date_year {
            width: 33%;
        }    
    </style>
{% endblock style %}

{% block title %}{% translate 'Creating single notification' %}{% endblock title %}

{% block content %}
    <section>
        {% include 'misc/includes/navbar.html' with user=user %}

        {% if only_inactive == user.choose_sending.count %}
            <div>
                <h5>{% translate 'Before you can create a notification, you need to connect one of your networks' %}. <a href="{% url 'auth:profile' %}">{% translate 'Connect' %}</a></h5>
            </div>
        {% else %}
            {% if user.is_subscribed or all_notifications < 10 %}
                <div>
                    {% crispy form %}
                </div>
            {% else %}
                <h1>{% translate 'To create more notifications, you need to be a sub' %}</h1>
            {% endif %}
        {% endif %}
    </section>
{% endblock content %}

notifications/templates/notifications/CUD_notifications/create_periodical_notification.html
{% extends 'base.html' %}
{% load i18n crispy_forms_tags %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Creating periodic notification' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Creating periodic notification' %}" />
    <meta property="og:url" content="{% url 'notifications:create_periodical_notification' %}" />
{% endblock meta_tags %}

{% block title %}{% translate 'Creating periodic notification' %}{% endblock title %}

{% block content %}
    <section>
        {% include 'misc/includes/navbar.html' with user=user %}

        {% if only_inactive == user.choose_sending.count %}
            <div>
                <h5>{% translate 'Before you can create a notification, you need to connect one of your networks' %}. <a href="{% url 'auth:profile' %}">{% translate 'Connect' %}</a></h5>
            </div>
        {% else %}
            {% if user.is_subscribed or all_notifications < 10 %}
                <div>
                    {% crispy form %}
                </div>
            {% else %}
                <h1>{% translate 'To create more notifications, you need to be a sub' %}</h1>
            {% endif %}
        {% endif %}
    </section>
{% endblock content %}

{% block script %}
    <script>
        let notification_time = document.getElementById('id_notification_periodicity_num');
        let label_notif_periodic = document.querySelector('label[for=id_notification_periodicity_num]')
        let every_day = document.getElementById('id_dates_type_1');
        let user_dates = document.getElementById('id_dates_type_2');
        let input_dates = document.getElementById('id_dates');
        input_dates.autocomplete = "off"
        let times = document.querySelector('.times');
        const today = new Date()
        let tomorrow =  new Date()
        tomorrow.setDate(today.getDate() + 1)

        function check() {
            if(every_day.checked) {
                label_notif_periodic.style.display = 'inline-block'
                notification_time.style.display = 'inline-block';
                input_dates.className = 'd-none'
                if (input_dates.value) {
                    input_dates.value = '';
                }
                datepicker = null;
            } else if (user_dates.checked) {
                label_notif_periodic.style.display = 'none';
                notification_time.style.display = 'none';
                input_dates.className = 'd-inline'
                if (notification_time.value) {
                    notification_time.value = 1;
                }
                let elem = document.querySelector('input[name="dates"]');
                let datepicker = new Datepicker(elem, {
                    maxNumberOfDates: 15,
                    minDate: tomorrow,
                    format: 'yyyy-mm-dd'
                }); 
            }
        }
    </script>
{% endblock script %}

notifications/templates/notifications/CUD_notifications/delete_notification_periodic.html
{% extends 'base.html' %}

{% load i18n %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Deleting periodic notification' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Deleting periodic notification' %}" />
    <meta property="og:url" content="{% url 'notifications:delete_periodic_notification' pk=notification.id %}" />
{% endblock meta_tags %}

{% block title %}{% translate 'Deleting periodic notification' %}{% endblock title %}

{% block content %}
    <section>
        {% include 'misc/includes/navbar.html' with user=user %}
        <div>
            <form action="" method="post">
                {% csrf_token %}
                <p>{% translate 'Are you sure you want to delete this notification?' %} <a href="{{ notification.get_url_path }}">{{ notification.title }}</a></p>
                <button class="btn btn-danger" type="submit">{% translate 'Delete' %}</button>
            </form>
        </div>
    </section>
{% endblock content %}

notifications/templates/notifications/CUD_notifications/delete_single_notification.html
{% extends 'base.html' %}

{% load i18n %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Deleting single notification' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Deleting single notification' %}" />
    <meta property="og:url" content="{% url 'notifications:delete_notification' pk=notification.id %}" />
{% endblock meta_tags %}

{% block title %}{% translate 'Deleting single notification' %}{% endblock title %}

{% block content %}
    <section>
        {% include 'misc/includes/navbar.html' with user=user %}
        <div>
            <form action="" method="post">
                {% csrf_token %}
                <p>{% translate 'Are you sure you want to delete this notification?' %} <a href="{{ notification.get_url_path }}">{{ notification.title }}</a></p>
                <button class="btn btn-danger" type="submit">{% translate 'Delete' %}</button>
            </form>
        </div>
    </section>
{% endblock content %}

notifications/templates/notifications/CUD_notifications/edit_notification.html
{% extends 'base.html' %}

{% load i18n crispy_forms_tags %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Editing single notification' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Editing single notification' %}" />

    <meta property="og:url" content="{% url 'notifications:edit_notification' pk=object.id %}" />
{% endblock meta_tags %}

{% block style %}
    <style>
        #div_id_notification_date > div {
            display: flex;
        }
        #id_notification_date_day, #id_notification_date_month, #id_notification_date_year {
            width: 33%;
        }      
    </style>
{% endblock style %}

{% block title %}{% translate 'Editing single notification' %}{% endblock title %}

{% block content %}
    <section>
        {% include 'misc/includes/navbar.html' with user=user %}
        <div>
            {% crispy form %}
        </div>
    </section>
{% endblock content %}

notifications/templates/notifications/CUD_notifications/edit_notification_periodic.html
{% extends 'base.html' %}

{% load i18n crispy_forms_tags %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Editing periodic notification' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Editing periodic notification' %}" />
    <meta property="og:url" content="{% url 'notifications:edit_periodic_notification' pk=object.id %}" />
{% endblock meta_tags %}


{% block title %}{% translate 'Editing periodic notification' %}{% endblock title %}

{% block content %}
    <section>
        {% include 'misc/includes/navbar.html' with user=user %}
        <div>
            {% crispy form %}
        </div>
    </section>
{% endblock content %}

{% block script %}
    <script>
        let notification_time = document.getElementById('id_notification_periodicity_num');
        let label_notif_periodic = document.querySelector('label[for=id_notification_periodicity_num]')
        let every_day = document.getElementById('id_dates_type_1');
        let user_dates = document.getElementById('id_dates_type_2');
        let input_dates = document.getElementById('id_dates');
        input_dates.autocomplete = "off"
        let times = document.querySelector('.times');
        const today = new Date()
        let tomorrow =  new Date()
        tomorrow.setDate(today.getDate() + 1)

        function check() {
            if(every_day.checked) {
                label_notif_periodic.style.display = 'inline-block'
                notification_time.style.display = 'inline-block';
                input_dates.className = 'd-none'
                if (input_dates.value) {
                    input_dates.value = '';
                }
                datepicker = null;
            } else if (user_dates.checked) {
                label_notif_periodic.style.display = 'none';
                notification_time.style.display = 'none';
                input_dates.className = 'd-inline'
                if (notification_time.value) {
                    notification_time.value = 1;
                }
                let elem = document.querySelector('input[name="dates"]');
                let datepicker = new Datepicker(elem, {
                    maxNumberOfDates: 15,
                    minDate: tomorrow,
                    format: 'yyyy-mm-dd'
                }); 
            }
        }
    </script>
{% endblock script %}