notifications/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from notifications.views import redirect_user_view


urlpatterns = i18n_patterns(
    path('', redirect_user_view, name="redirect_user_view"),
    path('admin/', admin.site.urls),

    # api notifications
    path('api_notifications/', include(('notifications.notifications_api.urls', 'notifications_api'), namespace="notifications_api")),

    # Notifications
    path('notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),

    # Notification Categories
    path('notification_categories/', include(('notification_categories.urls', 'notification_categories'), namespace='notification_categories')),

    # api notification categories
    path('api_notification_categories/', include(
            ('notification_categories.notification_categories_api.urls', 'notification_categories_api'),
            namespace='notification_categories_api'
        )
    ),

    # Auth
    path('api-auth/', include(('authentication.authentication_api.urls', 'api-auth'), namespace="api-auth")),


    path('auth/', include(('authentication.urls', 'auth'), namespace='auth')),

)

handler404 = 'core.views.not_found_404'
hhandler500 = 'core.views.server_error_500'

notifications/notification_categories/urls.py
from django.urls import path

from .views import (
    AddNotificationCategoryView,
    EditNotificationCategoryView,
    DeleteNotificationCategoryView,

)
app_name = 'notification_categories'
urlpatterns = [
    path('add_notification_category/', AddNotificationCategoryView.as_view(), name="add_notification_category"),
    path('edit_notification_category/<str:slug>/', EditNotificationCategoryView.as_view(), name="edit_notification_category"),
    path('delete_notification_category/<str:slug>/', DeleteNotificationCategoryView.as_view(), name="delete_notification_category"),
]

notifications/notifications/notifications_api/urls.py
from django.urls import path

from .api_views import (
    NotificationListApiView,
    NotificationFinishedListApiView,

    NotificationSingleDetailApiView, 
    NotificationSingleCreateApiView, 
    NotificationSingleEditApiView, 
    NotificationSingleDeleteApiView,

    NotificationPeriodicDetailApiView, 
    NotificationPeriodicCreateApiView,
    NotificationPeriodicDeleteApiView, 
    NotificationPeriodicEditApiView,

    NotificationPeriodicTimeStampsListApiView,
    NotificationPeriodicRevokeCertainTimeStampApiView,
    NotificationPeriodicRevokeAllTimeStampsApiView,

    ChangeNotificationStatusFromRevokeToIncompleteApi
)

app_name = "notifications_api"

urlpatterns = [
    path('notifications_list/', NotificationListApiView.as_view(), name='notifications_list_api'),
    path('finished_notifications_list/', NotificationFinishedListApiView.as_view(), name='finished_notifications_list_api'),

    path('create_notification_single/', NotificationSingleCreateApiView.as_view(), name='create_notification_single_api'),
    path('edit_notification_single/<uuid:pk>/', NotificationSingleEditApiView.as_view(), name='edit_notification_single_api'),
    path('delete_notification_single/<uuid:pk>/', NotificationSingleDeleteApiView.as_view(), name='delete_notification_single_api'),
    path('single/<uuid:pk>/', NotificationSingleDetailApiView.as_view(), name='notification_single_detail_api'),

    path('create_notification_periodic/', NotificationPeriodicCreateApiView.as_view(), name='create_notification_periodic_api'),
    path('delete_notification_periodic/<uuid:pk>/', NotificationPeriodicDeleteApiView.as_view(), name='delete_notification_periodic_api'),
    path('edit_notification_periodic/<uuid:pk>/', NotificationPeriodicEditApiView.as_view(), name='edit_notification_periodic_api'),
    path('periodic/<uuid:pk>/', NotificationPeriodicDetailApiView.as_view(), name='notification_periodic_detail_api'),

    path('notification_periodic_time_stamps_list/<uuid:pk>/', NotificationPeriodicTimeStampsListApiView.as_view(), name='notification_periodic_time_stamps_list_api'),
    path('revoke_certain_notification_time_stamp/<uuid:pk>/', NotificationPeriodicRevokeCertainTimeStampApiView.as_view(), name='notification_periodic_revoke_certain_time_stamp_api'),
    path('revoke_all_notification_time_stamp/<uuid:pk>/', NotificationPeriodicRevokeAllTimeStampsApiView.as_view(), name='notification_periodic_revoke_all_time_stamps_api'),

    path('change_notification_status_from_revoke_to_incomplete/<uuid:pk>/', ChangeNotificationStatusFromRevokeToIncompleteApi.as_view(), name='change_notification_status_from_revoke_to_incomplete_api')

]

notifications/notifications/urls.py
from django.urls import path
from .views import (
    NotificationListView,
    NotificationSingleCreateView,
    NotificationSingleEditView, 
    NotificationSingleDeleteView,
    NotificationSingleDetailView, 
    PeriodicalNotificationCreateView,
    NotificationPeriodicDetailView,
    NotificationPeriodicListTimeStampsView,
    NotificationPeriodicRevokeCertainTimeStampView,
    NotificationPeriodicRevokeAllTimeStampsView,
    notificatePeriodicNotificationOnlyForAdmin,
    notificateSingleNotificationOnlyForAdmin,
    NotificationPeriodicDeleteView,
    NotificationPeriodicEditView,
    NotificationFinishedListView,
    change_notification_status_from_revoke_to_incomplete,
    SearchNotificationView
)

app_name = 'notifications'

urlpatterns = [
    path('read/', NotificationListView.as_view(), name="notification_list"),
    path('finished/', NotificationFinishedListView.as_view(), name="notification_archive_list"),

    path('create/', NotificationSingleCreateView.as_view(), name="create_notification"),
    path('create_periodical_notification/', PeriodicalNotificationCreateView.as_view(), name="create_periodical_notification"),
    path('edit/<uuid:pk>/', NotificationSingleEditView.as_view(), name="edit_notification"),
    path('edit_periodic/<uuid:pk>/', NotificationPeriodicEditView.as_view(), name="edit_periodic_notification"),
    path('delete/<uuid:pk>/', NotificationSingleDeleteView.as_view(), name="delete_notification"),
    path('delete_periodic/<uuid:pk>/', NotificationPeriodicDeleteView.as_view(), name="delete_periodic_notification"),
    path('single/<uuid:pk>/', NotificationSingleDetailView.as_view(), name="detail_single_notification"),
    path('periodic/<uuid:pk>/', NotificationPeriodicDetailView.as_view(), name="detail_periodic_notification"),

    path('notification_periodic_time_stamps_list/<uuid:pk>/', NotificationPeriodicListTimeStampsView.as_view(), name="notification_periodic_time_stamps_list"),
    path('revoke_certain_time_stamp/detail/<uuid:pk>/', NotificationPeriodicRevokeCertainTimeStampView.as_view(), name="notification_periodic_revoke_certain_time_stamp"),
    path('revoke_all_time_stamps/<uuid:pk>/', NotificationPeriodicRevokeAllTimeStampsView.as_view(), name="notification_periodic_revoke_all_time_stamps"),

    path('notificate_periodic_notification_only_for_admin/<uuid:pk>/', notificatePeriodicNotificationOnlyForAdmin, name="notificate_periodic_notification_only_for_admin"),
    path('notificate_single_notification_only_for_admin/<uuid:pk>/', notificateSingleNotificationOnlyForAdmin, name="notificate_single_notification_only_for_admin"),

    path('change_notification_status_from_revoke_to_incomplete/<uuid:pk>/', change_notification_status_from_revoke_to_incomplete, name="change_notification_status_from_revoke_to_incomplete"),

    path('search/', SearchNotificationView.as_view(), name='search_results'),

]

notifications/notifications/views.py
from datetime import timedelta, datetime

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.decorators import permission_required, login_required
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.utils import timezone
from django.db.models.query_utils import Q
from django.utils.translation import get_language

from authentication.models import MyUser
from config.celery import app
from notification_categories.models import NotificationCategory

from .tasks import create_periodic_notification_task, create_notification_task
from .models import (
    NotificationBase, 
    NotificationPeriodicity, 
    NotificationSingle, 
    NotificationStatus, 
    NotificationId
)
from .forms import (
    NotificationCreateForm, 
    NotificationSingleEditForm, 
    PeriodicalNotificationCreateForm, 
    NotificationPeriodicEditForm, 
)

def redirect_user_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse_lazy('notifications:notification_list')) 
    else:
        return HttpResponseRedirect(reverse_lazy('auth:login')) 
        
class NotificationListView(LoginRequiredMixin, ListView):
    model = NotificationBase
    login_url = reverse_lazy('auth:login')
    template_name = 'notifications/notification_lists/notification_list.html'
    context_object_name = 'notifications'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['notifications_types'] = NotificationCategory.objects.filter(user=self.request.user)
        return context

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

class NotificationFinishedListView(LoginRequiredMixin, ListView):
    model = NotificationBase
    login_url = reverse_lazy('auth:login')
    template_name = 'notifications/notification_lists/notification_finished_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["finished_notifications"] = [notification for notification in self.get_queryset() if notification.check_all_notifications_are_complited() == True]
        context["finished_notifications_length"] = len(context["finished_notifications"])
        return context

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

class SearchNotificationView(LoginRequiredMixin, ListView):
    model = NotificationBase
    login_url = reverse_lazy('auth:login')
    context_object_name = "quotes"
    template_name = "notifications/search/search.html"
    context_object_name = "searched_notifications"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get("q")
        context["user"] = self.request.user
        if self.get_queryset():
            context["searched_notifications_length"] = len(self.get_queryset())
        else:
            context["searched_notifications_length"] = 0
        return context

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            singles = self.model.objects.filter(user=self.request.user).filter(notification_type="Single")
            singles = singles.filter((Q(notification_single__title__icontains=query) | Q(notification_single__text__icontains=query)))
            incomplited_singles = [notification_single for notification_single in singles if notification_single.check_all_notifications_are_complited() == False]

            periodics = self.model.objects.filter(Q(notification_type="Periodic") & Q(user=self.request.user))
            periodics = periodics.filter((Q(notification_periodic__title__icontains=query) | Q(notification_periodic__text__icontains=query)))
            incomplited_periodics = [notification_periodic for notification_periodic in periodics if notification_periodic.check_all_notifications_are_complited() == False]
            
            return incomplited_singles + incomplited_periodics

class NotificationSingleDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('auth:login')
    model = NotificationSingle
    template_name = 'notifications/detail/notification_single_detail.html'
    context_object_name = 'notification_single_detail'

    def get(self, request, *args, **kwargs):
        user = self.request.user
        notif_single = get_object_or_404(self.model, pk=self.kwargs['pk'])
        if user == notif_single.notification_type_single.user:
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse_lazy('notifications:notification_list'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_networks"] = (MyUser.objects.get(username=self.request.user.username).choose_sending.filter(active=True)).count()
        return context

class NotificationSingleCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('auth:login')
    model = NotificationSingle
    form_class = NotificationCreateForm
    template_name = 'notifications/CUD_notifications/create_notification.html'
    success_url = reverse_lazy('notifications:notification_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = MyUser.objects.get(username=self.request.user)
        context['all_notifications'] = NotificationBase.objects.filter(user=self.request.user).all().count()
        context['only_inactive'] = len(MyUser.objects.get(username=self.request.user.username).get_only_inactive_networks())
        return context

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw['user'] = self.request.user
        return kw

    def form_valid(self, form):
        notification_date = form.cleaned_data['notification_date']
        notification_time = form.cleaned_data['notification_time']
        time = str(notification_date) + ' ' + str(notification_time)
        time = datetime.strptime(time, '%Y-%m-%d %H:%M:%S')
        time = timezone.localtime(timezone.make_aware(time))

        notif_status = NotificationStatus.objects.create(time_stamp=time)
        notif_base = NotificationBase.objects.create(
            user=self.request.user,
            notification_type='Single'
        )
        self.model.objects.create(
            notification_category=form.cleaned_data['notification_category'],
            title=form.cleaned_data['title'],
            text=form.cleaned_data['text'],
            notification_date=form.cleaned_data['notification_date'],
            notification_time=form.cleaned_data['notification_time'],
            notification_status=notif_status,
            notification_type_single=notif_base
        )
        return HttpResponseRedirect(self.success_url)
        
class NotificationSingleEditView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('auth:login')
    model = NotificationSingle
    form_class = NotificationSingleEditForm
    template_name = 'notifications/CUD_notifications/edit_notification.html'
    success_url = reverse_lazy('notifications:notification_list')

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw['user'] = self.request.user
        return kw
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = MyUser.objects.get(username=self.request.user.username)
        return context
    
    def get(self, request, *args, **kwargs):
        user = self.request.user
        notif_single = get_object_or_404(self.model, pk=self.kwargs['pk'])
        if user == notif_single.notification_type_single.user:
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse_lazy('notifications:notification_list'))
        
    def form_valid(self, form):
        res = self.model.objects.get(pk=self.kwargs['pk'])
        time = str(form.cleaned_data['notification_date']) + ' ' + str(form.cleaned_data['notification_time'])
        time = datetime.strptime(time, '%Y-%m-%d %H:%M:%S')
        time = timezone.localtime(timezone.make_aware(time))

        NotificationStatus.objects.get(id=res.notification_status.id).delete()

        task = res.notification_status.notification_celery_id
        app.control.revoke(str(task), terminate=True, signal='SIGKILL')

        NotificationId.objects.get(notification_id=task).delete()

        res.notification_category = form.cleaned_data['notification_category']
        res.title = form.cleaned_data['title']
        res.text = form.cleaned_data['text']
        res.notification_time = form.cleaned_data['notification_time']
        res.notification_date = form.cleaned_data['notification_date']
        res.notification_status = NotificationStatus.objects.create(time_stamp=time)
        res.save()
        return HttpResponseRedirect(self.success_url)

class NotificationSingleDeleteView(LoginRequiredMixin, DeleteView):
    model = NotificationSingle
    success_url = reverse_lazy('notifications:notification_list')
    login_url = reverse_lazy('auth:login')
    template_name = 'notifications/CUD_notifications/delete_single_notification.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['notification'] = get_object_or_404(self.model, pk=self.kwargs['pk'])
        context['user'] = self.request.user
        return context
    
    def get(self, request, *args, **kwargs):
        user = self.request.user
        notif_single = get_object_or_404(self.model, pk=self.kwargs['pk'])

notifications/templates/notifications/notification_lists/notification_finished_list.html
{% extends 'base.html' %}

{% load i18n %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Your finished notifications' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Your finished notifications' %}" />
    <meta property="og:url" content="{% url 'notifications:notification_archive_list' %}" />
{% endblock meta_tags %}

{% block title %}{% translate 'Your finished notifications' %}{% endblock title %}

{% block content %}
    <section>
        {% include 'misc/includes/navbar.html' with user=user %}
        {% if finished_notifications_length >= 1 %}
            {% for notification in finished_notifications %}
                {% if notification.notification_type == 'Single' %}
                    <a href="{{ notification.notification_single.get_url_path }}" class="d-block my-3 text-decoration-none">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"  style="color: {{ notification.notification_single.notification_category.color }}">
                                    {{ notification.notification_single.notification_category.name_type }}
                                </h5>
                                <h3 class="card-subtitle text-dark">{{ notification.notification_single.title }}</h3>
                                <p class="card-text text-dark">{{ notification.notification_single.text }}</p>
                            </div>
                        </div>
                    </a>
                {% else %}
                    <a href="{{ notification.notification_periodic.get_url_path }}" class="d-block my-3 text-decoration-none">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title" style="color: {{ notification.notification_periodic.notification_category.color }}">
                                    {{ notification.notification_periodic.notification_category.name_type }}
                                </h5>
                                <h3 class="card-text text-dark">{{ notification.notification_periodic.title }}</h3>
                                <p class="card-text text-dark">{{ notification.notification_periodic.text }}</p>
                            </div>
                        </div>
                    </a>
                {% endif %}
            {% endfor %}
        {% else %}
            <h1 class="text-center position-absolute top-50 start-50 translate-middle text-dark fs-2">{% translate 'You don`t have any finished notifications.' %}</h1>
        {% endif %}
        </div>
    </section>
{% endblock content %}

notifications/templates/notifications/notification_lists/notification_list.html
{% extends 'base.html' %}

{% load i18n %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Your notifications' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Your notifications' %}" />
    <meta property="og:url" content="{% url 'notifications:notification_list' %}" />
{% endblock meta_tags %}

{% block title %}{% translate 'Your notifications' %}{% endblock title %}

{% block content %}
    <section>
        {% include 'misc/includes/navbar.html' with user=user %}
        <div>
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <a class="btn btn-outline-primary m-2" href="{% url 'notifications:create_notification' %}">{% translate 'Create single notification' %}</a>
                    <a class="btn btn-outline-primary m-2" href="{% url 'notifications:create_periodical_notification' %}">{% translate 'Create periodic notification' %}</a>
                    <a class="btn btn-outline-primary m-2" href="{% url 'notifications:notification_archive_list' %}">{% translate 'Your finished notifications' %}</a>
                </div>
                <a class="btn btn-outline-primary m-2" href="{% url 'notification_categories:add_notification_category' %}">{% translate 'Add a new category for notifications' %}</a>
            </div>
            <div class="d-flex justify-content-center align-items-center">
                <form class="input-group w-50" action="{% url 'notifications:search_results' %}" method="get">
                    <input
                      type="search"
                      name="q"
                      placeholder="{% translate 'Search incomplited notifications by title or text...' %}"
                      class="form-control"
                      maxlength="350"
                    />
                    <button type="submit" class="btn btn-outline-primary">{% translate 'Search' %}</button>
                  </form>
            </div>
            {% if notifications.count >= 1 %}
                {% for notification in notifications %}
                    {% if notification.check_all_notifications_are_complited == False %}
                        {% if notification.notification_type == 'Single' %}
                            <a href="{{ notification.notification_single.get_url_path }}" class="d-block my-3 text-decoration-none">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title"  style="color: {{ notification.notification_single.notification_category.color }}">
                                            {{ notification.notification_single.notification_category.name_type }}
                                        </h5>
                                        <h3 class="card-subtitle text-dark">{{ notification.notification_single.title }}</h3>
                                        <p class="card-text text-dark">{{ notification.notification_single.text }}</p>
                                    </div>
                                </div>
                            </a>
                        {% else %}
                            <a href="{{ notification.notification_periodic.get_url_path }}" class="d-block my-3 text-decoration-none">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title" style="color: {{ notification.notification_periodic.notification_category.color }}">
                                            {{ notification.notification_periodic.notification_category.name_type }}
                                        </h5>
                                        <h3 class="card-text text-dark">{{ notification.notification_periodic.title }}</h3>
                                        <p class="card-text text-dark">{{ notification.notification_periodic.text }}</p>
                                    </div>
                                </div>
                            </a>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            {% else %}
                <h1 class="text-center position-absolute top-50 start-50 translate-middle text-dark fs-2">{% translate 'You don`t have any active notifications yet' %}</h1>
            {% endif %}
        </div>
    </section>
{% endblock content %}