notifications/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from notifications.views import redirect_user_view


urlpatterns = i18n_patterns(
    path('', redirect_user_view, name="redirect_user_view"),
    path('admin/', admin.site.urls),

    # api notifications
    path('api_notifications/', include(('notifications.notifications_api.urls', 'notifications_api'), namespace="notifications_api")),

    # Notifications
    path('notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),

    # Notification Categories
    path('notification_categories/', include(('notification_categories.urls', 'notification_categories'), namespace='notification_categories')),

    # api notification categories
    path('api_notification_categories/', include(
            ('notification_categories.notification_categories_api.urls', 'notification_categories_api'),
            namespace='notification_categories_api'
        )
    ),

    # Auth
    path('api-auth/', include(('authentication.authentication_api.urls', 'api-auth'), namespace="api-auth")),


    path('auth/', include(('authentication.urls', 'auth'), namespace='auth')),

)

handler404 = 'core.views.not_found_404'
hhandler500 = 'core.views.server_error_500'

notifications/notification_categories/notification_categories_api/urls.py
from django.urls import path

from .api_views import AddNotificationCategoryApiView, NotificationCategoryEditApiView, NotificationCategoryDeleteApiView

app_name = "notification_categories_api"

urlpatterns = [
    path('create_notification_category_api/', AddNotificationCategoryApiView.as_view(), name='create_notification_category_api'),
    path('edit_notification_category_api/<str:slug>/', NotificationCategoryEditApiView.as_view(), name='edit_notification_category_api'),
    path('delete_notification_category_api/<str:slug>/', NotificationCategoryDeleteApiView.as_view(), name='delete_notification_category_api'),

]

notifications/notification_categories/urls.py
from django.urls import path

from .views import (
    AddNotificationCategoryView,
    EditNotificationCategoryView,
    DeleteNotificationCategoryView,

)
app_name = 'notification_categories'
urlpatterns = [
    path('add_notification_category/', AddNotificationCategoryView.as_view(), name="add_notification_category"),
    path('edit_notification_category/<str:slug>/', EditNotificationCategoryView.as_view(), name="edit_notification_category"),
    path('delete_notification_category/<str:slug>/', DeleteNotificationCategoryView.as_view(), name="delete_notification_category"),
]

notifications/notification_categories/models.py
from django.db import models

from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

class NotificationCategory(models.Model):
    # A model of the notification category, for example, study
    user = models.ForeignKey(
        'authentication.MyUser', 
        null=True, 
        on_delete=models.SET_NULL,
        verbose_name=_("User"),
    ) 
    name_type = models.CharField( # the category name
        _("Category name"),
        max_length=15
    )
    color = models.CharField( # category color
        _("Color"), 
        max_length=15
    )
    slug = models.SlugField(_("Slug"), allow_unicode=True)

    class Meta:
        verbose_name = 'Notification category'
        verbose_name_plural = 'Notification categories'

    def __str__(self):
        return self.name_type
    
    def save(self, *args, **kwargs):
        if not self.slug and self.name_type not in ['study', 'work', 'sport']:
            self.slug = slugify(self.name_type, allow_unicode=True)
        return super().save(*args, **kwargs)

notifications/notification_categories/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.db.models import Q

from crispy_forms import helper, layout

from .models import NotificationCategory

class AddNotificationCategoryForm(forms.ModelForm):
    class Meta:
        model = NotificationCategory
        fields = ['name_type', 'color']        
        labels = {
            'name_type' : _('Category name'),
        }
        widgets = {
            'color': forms.TextInput(attrs={'type': 'color'})
        }
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)
        name_type_field = layout.Field(
            'name_type', css_class="form-group", placeholder=_("Category name"),
        )
        color_field = layout.Field(
            'color', css_class="form-group mt-1",
        )
        submit_button = layout.Submit('submit', _('Create category'), css_class='btn btn-primary mt-2')

        self.helper = helper.FormHelper()
        self.helper.form_class = 'form-inline w-25'
        self.helper.form_method = 'post'
        self.helper.layout = layout.Layout(
            layout.Row(
                layout.Column(name_type_field, css_class="form-group col-9 mb-0"),
                layout.Column(color_field, css_class="form-group col-3 mb-0"),
                css_class="row"
            ),
            submit_button
        )

    def clean(self):
        name_type = self.cleaned_data['name_type']
        color = self.cleaned_data['color']
        if NotificationCategory.objects.filter(Q(user=self.request.user) | Q(user=None)).filter(Q(name_type=name_type) | Q(color=color)).exists():
            raise forms.ValidationError(_('Choose a different color or a different name for the notification type as it already exists'))

class EditNotificationCategoryForm(forms.ModelForm):
    class Meta:
        model = NotificationCategory
        fields = ['name_type', 'color']        
        labels = {
            'name_type' : _('Category name'),
        }
        widgets = {
            'color': forms.TextInput(attrs={'type': 'color'})
        }
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)
        name_type_field = layout.Field(
            'name_type', css_class="form-group", placeholder=_("Category name"),
        )
        color_field = layout.Field(
            'color', css_class="form-group mt-1",
        )
        submit_button = layout.Submit('submit', _('Edit category'), css_class='btn btn-primary mt-2')

        self.helper = helper.FormHelper()
        self.helper.form_class = 'form-inline w-25'
        self.helper.form_method = 'post'
        self.helper.layout = layout.Layout(
            layout.Row(
                layout.Column(name_type_field, css_class="form-group col-9 mb-0"),
                layout.Column(color_field, css_class="form-group col-3 mb-0"),
                css_class="row"
            ),
            submit_button
        )


    def clean(self):
        name_type = self.cleaned_data['name_type']
        color = self.cleaned_data['color']
        if NotificationCategory.objects.filter(Q(user=self.request.user) | Q(user=None)).filter(Q(name_type=name_type) | Q(color=color)).exists():
            raise forms.ValidationError(_('Choose a different color or a different name for the notification type as it already exists'))

notifications/notification_categories/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import NotificationCategory
from .forms import AddNotificationCategoryForm, EditNotificationCategoryForm

class AddNotificationCategoryView(LoginRequiredMixin, CreateView):
    ''' Страница создания категории для оповещения '''
    model = NotificationCategory
    form_class = AddNotificationCategoryForm
    success_url = reverse_lazy('auth:profile')
    login_url = reverse_lazy('auth:login')
    template_name = 'notification_categories/add_new_notification_category.html'

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw['request'] = self.request
        return kw

    def form_valid(self, form):
        notif_type = self.model.objects.create(user=self.request.user, name_type=form.cleaned_data['name_type'], color=form.cleaned_data['color'])
        notif_type.save()
        return HttpResponseRedirect(self.success_url)

class EditNotificationCategoryView(LoginRequiredMixin, UpdateView):
    ''' Страница редактирования категории для оповещения '''
    model = NotificationCategory
    form_class = EditNotificationCategoryForm
    success_url = reverse_lazy('auth:profile')
    login_url = reverse_lazy('auth:login')
    template_name = 'notification_categories/edit_notification_category.html'

    def get(self, request, *args, **kwargs):
        notif_type = self.model.objects.get(slug=kwargs['slug'])
        if self.request.user == notif_type.user:
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(self.success_url)
            
    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw['request'] = self.request
        return kw

class DeleteNotificationCategoryView(LoginRequiredMixin, DeleteView):
    ''' Страница удаления категории для оповещения '''
    model = NotificationCategory
    success_url = reverse_lazy('auth:profile')
    login_url = reverse_lazy('auth:login')
    template_name = 'notification_categories/delete_notification_category.html'
    context_object_name = 'category'

    def get(self, request, *args, **kwargs):
        notif_type = self.model.objects.get(slug=kwargs['slug'])
        if self.request.user == notif_type.user:
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(self.success_url)

notifications/templates/notification_categories/add_new_notification_category.html
{% extends 'base.html' %}

{% load i18n crispy_forms_tags %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Add a new category for notifications' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Add a new category for notifications' %}" />
    <meta property="og:url" content="{% url 'notification_categories:add_notification_category' %}" />
{% endblock meta_tags %}

{% block title %}{% translate 'Add a new category for notifications' %}{% endblock title %}

{% block content %}
<section>
    {% include 'misc/includes/navbar.html' with user=user %}
    <div>
        {% crispy form %}
    </div>
</section>
{% endblock content %}

notifications/templates/notification_categories/delete_notification_category.html
{% extends 'base.html' %}

{% load i18n %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Deleting notification category' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Deleting notification category' %}" />
    <meta property="og:url" content="{% url 'notification_categories:delete_notification_category' slug=category.slug %}" />
{% endblock meta_tags %}

{% block title %}{% translate 'Deleting notification category' %}{% endblock title %}

{% block content %}
    <section>
        {% include 'misc/includes/navbar.html' with user=user %}
        <div>
            <h4>{% translate 'Are you sure you want to delete this notification category' %}? - <span style="color: {{ category.color }};">{{ category.name_type }}</span></h4>
            <form action="" method="post">
                {% csrf_token %}
                <button type="submit">{% translate 'Delete' %}</button>
            </form>
        </div>
    </section>
{% endblock content %}

notifications/templates/notification_categories/edit_notification_category.html
{% extends 'base.html' %}

{% load i18n crispy_forms_tags %}

{% block meta_tags %}
    <meta name="description" content="{% translate 'Editing notification category' %}">
    <meta name="og:site_name" content="Notifications">
    <meta property="og:description" content="{% translate 'Editing notification category' %}" />
    <meta property="og:url" content="{% url 'notification_categories:edit_notification_category' slug=object.slug %}" />
{% endblock meta_tags %}

{% block title %}{% translate 'Editing notification category' %}{% endblock title %}

{% block content %}
<section>
    {% include 'misc/includes/navbar.html' with user=user %}
    <div>
        {% crispy form %}
    </div>
</section>
{% endblock content %}